version: '3'
volumes:
  dados:
services:
  db:
    image: postgres:12
    container_name: bd_bootsantander
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data